project_id = "opsnow-qa-automation"
region = "asia-northeast3"
zone = "asia-northeast3-a"
instance_name = "terraform-external-sy-instance"
instance_type = "e2-micro"
instance_image = "debian-10-buster-v20220719"
vpc_name = "terraform-external-sy-network"
